import sqlite3
import datetime
from fpdf import FPDF
import urllib.parse
import os

DB_PATH = 'history.db'

def save_to_history(crop, target_yield, fn, fp, fk, urea, ssp, mop, is_organic=False, land_area=1.0, area_unit="Hectares"):
    """
    Saves the recommendation details to a local SQLite database.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS recommendations (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            date TEXT,
            crop TEXT,
            target_yield REAL,
            fn REAL,
            fp REAL,
            fk REAL,
            urea REAL,
            ssp REAL,
            mop REAL,
            is_organic BOOLEAN,
            land_area REAL,
            area_unit TEXT
        )
    ''')
    
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cursor.execute('''
        INSERT INTO recommendations (date, crop, target_yield, fn, fp, fk, urea, ssp, mop, is_organic, land_area, area_unit)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ''', (now, crop, target_yield, fn, fp, fk, urea, ssp, mop, is_organic, land_area, area_unit))
    
    conn.commit()
    conn.close()

def generate_pdf_report(crop, target_yield, urea, ssp, mop, land_area, area_unit, is_organic=False, organic_fym=0, org_msg=None):
    """
    Generates a PDF prescription card using fpdf2.
    Returns the file path to the generated PDF.
    """
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "AgriSutra NE - Fertilizer Prescription", ln=True, align="C")
    pdf.ln(5)
    
    # Details
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d')}", ln=True)
    pdf.cell(0, 8, f"Crop: {crop}", ln=True)
    pdf.cell(0, 8, f"Target Yield: {target_yield} q/ha", ln=True)
    pdf.cell(0, 8, f"Plot Size: {land_area} {area_unit}", ln=True)
    pdf.ln(5)
    
    # Recommendations
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Recommended Fertilizers (Total for plot)", ln=True)
    pdf.set_font("helvetica", "", 12)
    
    pdf.cell(0, 8, f"Urea: {urea} kg", ln=True)
    pdf.cell(0, 8, f"SSP: {ssp} kg", ln=True)
    pdf.cell(0, 8, f"MOP: {mop} kg", ln=True)
    
    if is_organic and organic_fym:
        pdf.ln(3)
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 8, f"Organic Pathway Selected:", ln=True)
        pdf.set_font("helvetica", "", 12)
        pdf.cell(0, 8, f"Farmyard Manure (FYM): {round(organic_fym * land_area, 2)} tonnes", ln=True)
        if org_msg:
            pdf.multi_cell(0, 8, f"Note: {org_msg}")
            
    # Footer
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 10)
    pdf.cell(0, 10, "Generated by AgriSutra NE - Built for the soil, by the science, for the farmer.", ln=True, align="C")
    
    filename = f"prescription_{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}.pdf"
    pdf.output(filename)
    return filename

def get_whatsapp_link(crop, target_yield, urea, ssp, mop, land_area, area_unit):
    """
    Generates a wa.me link with a pre-filled WhatsApp message.
    """
    msg = f"🌾 AgriSutra NE Fertilizer Prescription 🌾\n\n"
    msg += f"Crop: {crop}\n"
    msg += f"Target Yield: {target_yield} q/ha\n"
    msg += f"Plot Size: {land_area} {area_unit}\n\n"
    msg += f"Required Fertilizers:\n"
    msg += f"🧪 Urea: {urea} kg\n"
    msg += f"🧪 SSP: {ssp} kg\n"
    msg += f"🧪 MOP: {mop} kg\n\n"
    msg += "Thank you for using AgriSutra NE!"
    
    encoded_msg = urllib.parse.quote(msg)
    return f"https://wa.me/?text={encoded_msg}"
